name: silme
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.2
  flutter_hooks: ^0.20.2
  hooks_riverpod: ^2.4.2
  riverpod_annotation: ^2.1.4
  go_router: ^11.1.2
  shared_preferences: ^2.2.1
  very_good_analysis: ^5.1.0
  flutter_native_splash: ^2.3.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  riverpod_generator: ^2.3.1
  riverpod_lint: ^2.0.3
  custom_lint: ^0.5.3
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6

flutter_native_splash:
  color: "#ffffff"
  image: assets/splash.png

flutter:

  uses-material-design: true

  assets:
      - assets/
      - assets/images/

  # fonts:
  #   - family: poppins
  #     fonts:
  #       - asset: assets/fonts/poppins.ttf